name: Tests

on:
  push:
    branches:
      - "v*" # This triggers the workflow for pushes to any branch ...
  pull_request:
    branches:
      - "v*" # ... and for pull requests.

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18" # ensure compatibility with go v1.18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go mod tidy
      - name: Test with Coverage
        run: go test -coverprofile=coverage.out ./...
      - name: Ensure 100% Coverage
        run: |
          go tool cover -func=coverage.out | grep -E 'total:\s+\(statements\)\s+100.0%'
